---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
# comment for testing
include:
  - project: nci-gdc/gitlab-templates
    ref: 0.5.1
    file:
      - templates/global/full.yaml

variables:
  BASE_CONTAINER_VERSION: 3.5.0
  PRE_COMMIT_DOCKER_IMAGE: ${BASE_CONTAINER_REGISTRY}/python3.13-builder:${BASE_CONTAINER_VERSION}
  PRE_COMMIT_VERSION: 4.3.0

# build_dockers:
#   stage: build
#   services:
#     - docker:${DOCKER_VERSION}-dind
#   tags:
#     - dind
#   image: docker:${DOCKER_VERSION}-dind
#   before_script:
#     - docker info
#     - apk add --no-cache bash moreutils git go curl just
#   variables:
#     BASE_CONTAINER_REGISTRY: "docker.osdc.io"
#   script:
#     - /bin/bash build.sh -b "$CI_COMMIT_BRANCH" -n "$CI_COMMIT_SHORT_SHA"
